name: Build and Deploy site

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Install
      run: npm install

    - name: Build App
      run: npm run build

    - name: Build Sitemap
      run: npm run sitemap

    - name: 404 handling
      run: cp dist/index.html dist/404.html

    - name: Install SSH Client
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        ssh-key: true
        folder: 'dist'
        clean: true
